### ISSUE TITLE
How about adding traits for Response and Request?

### ISSUE THREAD

**Issue by schmunk42** [albertborsos/yii2-pjax#1]
Thank you for creating this. Just two ideas from my side...

How about adding traits for Response and Request?
So the functionality could be more easily used in custom classes.
Also they could implement a `PjaxRespsonseInterface` and the widget can do a check on this, to avoid using the widgets without having a proper configuration.

**Comment by albertborsos** [comment]
You're welcome.

You mean move both methods from the classes into traits?
The interface is a good idea.

**Comment by schmunk42** [comment]
Not both into the same trait, like `PjaxRequestTrait` and `PjaxResponseTrait`, Request could actually be a behavior, but Response not - as far as I see - but I'd find it confusing if one would be a Behavior and the other a Trait.

**Comment by albertborsos** [comment]
Yes, sorry I meant two traits, just mistyped it.
I can implement it soon. Thanks for the advice!

**Comment by albertborsos** [comment]
Done!
