### ISSUE TITLE
pjax events

### ISSUE THREAD

**Issue by bscheshir** [albertborsos/yii2-pjax#2]
I want to use pjax events.
This is good time to add event like jui widgets
https://github.com/yiisoft/yii2-jui/blob/bd5e99bc0cc58b1067ccaab9a3ff2417e414b284/src/Widget.php#L32-L48
```php
    /**
     * @var array the event handlers for the underlying jQuery UI widget.
     * Please refer to the corresponding jQuery UI widget Web page for possible events.
     * For example, [this page](http://api.jqueryui.com/accordion/) shows
     * how to use the "Accordion" widget and the supported events (e.g. "create").
     * Keys are the event names and values are javascript code that is passed to the `.on()` function
     * as the event handler.
     *
     * For example you could write the following in your widget configuration:
     *
     * ```php
     * 'clientEvents' => [
     *     'change' => 'function () { alert('event "change" occured.'); }'
     * ],
     * ```
     */
    public $clientEvents = [];
```
https://github.com/yiisoft/yii2-jui/blob/bd5e99bc0cc58b1067ccaab9a3ff2417e414b284/src/Widget.php#L83-L117
```php
    /**
     * Registers a specific jQuery UI widget events
     * @param string $name the name of the jQuery UI widget
     * @param string $id the ID of the widget
     */
    protected function registerClientEvents($name, $id)
    {
        if (!empty($this->clientEvents)) {
            $js = [];
            foreach ($this->clientEvents as $event => $handler) {
                if (isset($this->clientEventMap[$event])) {
                    $eventName = $this->clientEventMap[$event];
                } else {
                    $eventName = strtolower($name . $event);
                }
                $js[] = "jQuery('#$id').on('$eventName', $handler);";
            }
            $this->getView()->registerJs(implode("\n", $js));
        }
    }

    /**
     * Registers a specific jQuery UI widget asset bundle, initializes it with client options and registers related events
     * @param string $name the name of the jQuery UI widget
     * @param string $id the ID of the widget. If null, it will use the `id` value of [[options]].
     */
    protected function registerWidget($name, $id = null)
    {
        if ($id === null) {
            $id = $this->options['id'];
        }
        JuiAsset::register($this->getView());
        $this->registerClientEvents($name, $id);
        $this->registerClientOptions($name, $id);
    }
```

https://github.com/defunkt/jquery-pjax readme

event | cancel | arguments | notes
-- | -- | -- | --
pjax:click | ✔︎ | options | fires from a link that got activated; cancel to prevent pjax
pjax:beforeSend | ✔︎ | xhr, options | can set XHR headers
pjax:start |   | xhr, options |  
pjax:send |   | xhr, options |  
pjax:clicked |   | options | fires after pjax has started from a link that got clicked
pjax:beforeReplace |   | contents, options | before replacing HTML with content loaded from the server
pjax:success |   | xhr, data, status, options | after replacing HTML content loaded from the server
pjax:timeout | ✔︎ | xhr, options | fires after options.timeout; will hard refresh unless canceled
pjax:error | ✔︎ | xhr, textStatus, error, options | on ajax error; will hard refresh unless canceled
pjax:complete |   | xhr, textStatus, options | always fires after ajax, regardless of result
pjax:end |   | xhr, options |  
pjax:popstate |   |   | event direction property: "back"/"forward"
pjax:start |   | null, options | before replacing content
pjax:beforeReplace |   | contents, options | right before replacing HTML with content from cache
pjax:end |   | null, options | after replacing content

**Comment by albertborsos** [comment]
Can you show at least one use case for a pjax event what you want to use? Thanks.

**Comment by bscheshir** [comment]
I try tu sue nested pjax: 1 inner pjax work with modal form and redraw form with error, outer will redraw a table whithin result of successful commit modal form. I wish to `pjax:success` or `pjax:complete` from inner pjax to run `$.pjax({url: url, container: '#pjax-container'})`

**Comment by albertborsos** [comment]
You can skip the inner pjax with a simple ajax validation:
https://www.yiiframework.com/doc/guide/2.0/en/input-validation#ajax-validation

I have an application with the same use case. I simply do a redirect on successful form commit. I cannot promise that I will have time to try this out. If you have capacity, then PRs are welcome :)

**Comment by bscheshir** [comment]
This is different matter. But I try it... If I will have a lot of time.

**Comment by albertborsos** [comment]
Today I ran into the same issue, when I needed to refresh the sidebar menu after a pjax request. So I implemented it. I will push it to the yii2 core repository too.
